### ISSUE TITLE
[bug]: Rainbow Wallet Connection failed

### ISSUE THREAD

**Issue by mertcankose** [WalletConnect/react-native-examples#103]
### Description

When I want to connect to rainbow wallet from my dapp, I get the following error.

Connection Failed
Something went wrong. Please try again, or reach out to our support team.

Non conforming namespaces.approve() namespaces methods don't satisfy namespace methods for eip155:1

MY SESSION OBJECT

export const sessionParams = {
  namespaces: {
    eip155: {
      methods: [
        'eth_sendTransaction',
        'personal_sign',
        'wallet_addEthereumChain',
        'wallet_switchEthereumChain',
        'eth_chainId',
      ],
      chains: [
        // 'eip155:11155111', //sepolia
        'eip155:1', //eth
      ],
      events: ['chainChanged', 'accountsChanged', 'connect', 'disconnect'],
      rpcMap: {},
    },
  },
  optionalNamespaces: {
    eip155: {
      methods: [
        'eth_sendTransaction',
        'personal_sign',
        'wallet_addEthereumChain',
        'wallet_switchEthereumChain',
        'eth_chainId',
      ],
      chains: [
        'eip155:137', //polygon
        'eip155:56', //bsc
      ],
      events: ['chainChanged', 'accountsChanged', 'connect', 'disconnect'],
      rpcMap: {},
    },
  },
};

### Issue Environment

- [ ] dapps/v2Explorer
- [ ] wallets/rn_cli_wallet
- [ ] wallets/rn_cli_wallet_068_5
- [ ] wallets/expo_wallet
- [ ] wallets/web3wallet_tutorial
- [X] In my own code

### Output of `npx react-native info`

System:
  OS: macOS 13.5.2
  CPU: (8) arm64 Apple M1
  Memory: 75.80 MB / 8.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 16.17.1
    path: ~/.nvm/versions/node/v16.17.1/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.nvm/versions/node/v16.17.1/bin/yarn
  npm:
    version: 8.15.0
    path: ~/.nvm/versions/node/v16.17.1/bin/npm
  Watchman:
    version: 2023.09.04.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.1
    path: /Users/mertcankose/.rvm/gems/ruby-2.7.6/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.0
      - iOS 17.0
      - macOS 14.0
      - tvOS 17.0
      - watchOS 10.0
  Android SDK: Not Found
IDEs:
  Android Studio: 2021.3 AI-213.7172.25.2113.9014738
  Xcode:
    version: 15.0/15A240d
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 11.0.16.1
    path: /usr/bin/javac
  Ruby:
    version: 2.7.6
    path: /Users/mertcankose/.rvm/rubies/ruby-2.7.6/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false

### Steps to reproduce

Dapp -> Connect Wallet -> Rainbow Wallet -> Error

### Snack, code example, screenshot, or link to a repository

![rainbow](https://github.com/WalletConnect/react-native-examples/assets/56760896/969e2992-a5df-4f65-b603-f9884c383180)

**Comment by ignaciosantise** [comment]
Hey @mertcankose the problem is because you are sending some methods that rainbow doesn't support.
I recommend sending methods inside `optionalNamespaces` except for `'eth_sendTransaction', 'personal_sign'`

Something like this:
```
export const sessionParams = {
  namespaces: {
    eip155: {
      methods: ['eth_sendTransaction', 'personal_sign'],
      chains: [
        'eip155:1' //eth
      ],
      events: ['chainChanged', 'accountsChanged', 'connect', 'disconnect'],
      rpcMap: {}
    }
  },
  optionalNamespaces: {
    eip155: {
      methods: ['wallet_addEthereumChain', 'wallet_switchEthereumChain', 'eth_chainId'],
      chains: [
        'eip155:137', //polygon
        'eip155:56' //bsc
      ],
      events: ['chainChanged', 'accountsChanged', 'connect', 'disconnect'],
      rpcMap: {}
    }
  }
};
```

Feel free to reopen if the issue persists.
