### ISSUE TITLE
rn_expo_wallet example does not work with web

### ISSUE THREAD

**Issue by OhRobin** [WalletConnect/react-native-examples#11]
rn_expo_wallet example does not work with web and iOS example does not correctly set the appropriate "projectId" and "relayUrl"

**Comment by crypblizz8** [comment]
Hey there @OhRobin, can you provide more details as the error that you encountered. Thanks

**Comment by OhRobin** [comment]
@crypblizz8 there are no errors, but when i run `yarn` with web, there are nothing that is displayed on screen

**Comment by OhRobin** [comment]
it would be helpful to know if this example is completely deprecated and I should be following https://github.com/WalletConnect/web-examples/tree/main/dapps/react-dapp-v2-with-ethers instead

**Comment by crypblizz8** [comment]
Makes sense @OhRobin . This repo is still a WIP and won't be deprecated as this is V2. 

Will look into the `web` side as we prioritised `ios` and `android` for now. So you are looking to use your codebase across all 3 platforms?

If you are just using `web` and for the `dApp `side that repo you mentioned would be most suitable. This is a wallet repo. Am currently working on the `dApp` + `React Native` side

**Comment by ignaciosantise** [comment]
@OhRobin as crypblizz8 said, our focus now is on Android and iOS. You can check https://github.com/WalletConnect/web3modal for web examples.
