### ISSUE TITLE
dapps/v2Explorer: Cannot find MetaMask on Android

### ISSUE THREAD

**Issue by doutv** [WalletConnect/react-native-examples#16]
I cannot find MetaMask on the popup modal after I click "Connect Wallet". Can someone help me?

**Comment by doutv** [comment]
Oh, I find the reason here: https://github.com/WalletConnect/react-native-examples/blob/a6bf70a90f9ce81a0ba2db15740838b1871f8643/dapps/v2Explorer/src/utils/ExplorerUtils.tsx#L50

If I change to v2 `https://explorer-api.walletconnect.com/v2/wallets?projectId=${ENV_PROJECT_ID}&sdks=sign_v2&entries=7&page=1`, MetaMask will appear.

**Comment by doutv** [comment]
However, after I click MetaMask, MetaMask app is raised, there is no message for me to sign, and I cannot go back to the example dapp.

**Comment by laurenkumar** [comment]
After looking at the API, it seems that metamask use the version one of the sdk, "sdks":["sign_v1"]. It must be another way to connect to sdk v1.
I'm trying too to connect to metamask

**Comment by crypblizz8** [comment]
This repo has been setup to work with V2 Wallets. Metamask is still working on the V2 integration.

Is it correct to assume you want to use V1 wallets in this? Then I would suggest using [react-native-dapp](https://github.com/WalletConnect/walletconnect-monorepo/tree/v1.0/packages/helpers/react-native-dapp) which is part of v1

**Comment by laurenkumar** [comment]
No I actually would like both. Or make an exception for metamask

**Comment by rafaeluzzi** [comment]
> This repo has been setup to work with V2 Wallets. Metamask is still working on the V2 integration.
> 
> Is it correct to assume you want to use V1 wallets in this? Then I would suggest using [react-native-dapp](https://github.com/WalletConnect/walletconnect-monorepo/tree/v1.0/packages/helpers/react-native-dapp) which is part of v1

@crypblizz8 any idea how close is Metamask to finishing their V2 integration? The big issue with V1 [react-native-dapp](https://github.com/WalletConnect/walletconnect-monorepo/tree/v1.0/packages/helpers/react-native-dapp) deep link with the Metamask app isn't working, it goes straight to the apple store every time.

**Comment by crypblizz8** [comment]
Hey hopefully they are close! You can follow the thread [here](https://github.com/MetaMask/metamask-mobile/issues/3957#issuecomment-1535544915) + would be great to upvote it! Closing issue.
