### ISSUE TITLE
dapps/v2Explorer: TypeError: Cannot read property 'getItem' of undefined

### ISSUE THREAD

**Issue by idlatest** [WalletConnect/react-native-examples#26]
I am getting this error when I call `signer.signMessage('message')`

**Comment by crypblizz8** [comment]
Will investigate this. More context in Discord available [here](https://discord.com/channels/492410046307631105/1085673920365068368):

**Comment by idlatest** [comment]
Okay thanks @crypblizz8

**Comment by zocial-rajesh** [comment]
Any update, as I am facing the same issue....

**Comment by ignaciosantise** [comment]
Hey 👋 this [PR](https://github.com/WalletConnect/walletconnect-monorepo/pull/2234) should fix the issue with `getItem` 🎉 🎉  to test it, you can install the canary release `2.7.0-rc-3`

**Comment by ignaciosantise** [comment]
Let us know if that version of the universal provider works @idlatest @zocial-rajesh @pavandugariya

**Comment by idlatest** [comment]
Thank you @ignaciosantise I will test this out later today and see if it works.

**Comment by zocial-rajesh** [comment]
'getItem' is resolved but got a new one 
![Screenshot 2023-04-18 at 7 51 52 PM](https://user-images.githubusercontent.com/103043549/232807022-1aa3fbea-b461-4536-a976-f77034f15f91.png)

**Comment by ignaciosantise** [comment]
@zocial-rajesh Yes, that's because the universal provider requires the key `WALLETCONNECT_DEEPLINK_CHOICE` to be setted.

You need to set it when the user presses a wallet: 
`AsyncStorage.setItem(
      'WALLETCONNECT_DEEPLINK_CHOICE',
      JSON.stringify({href: wallet.mobile.universal}),
    );`

`wallet.mobile.universal` is the link of the wallet, for example: `https://link.trustwallet.com`

**Comment by zocial-rajesh** [comment]
Thank you. it's working!

**Comment by idlatest** [comment]
It's now working @ignaciosantise. For anyone wondering where to put `AsyncStorage.setItem('WALLETCONNECT_DEEPLINK_CHOICE', JSON.stringify({href: wallet.mobile.universal}));`

If you are using the example in this repository, go to the `ExplorerItem` component inside the 'components' folder and update the `onPress` function to 

```
const onPress = async () => {
		await AsyncStorage.setItem(
			'WALLETCONNECT_DEEPLINK_CHOICE',
			JSON.stringify({ href: walletInfo.mobile.universal })
		);
		navigateDeepLink(
			walletInfo.mobile.universal,
			walletInfo.mobile.native,
			currentWCURI
		);
	};
	```

**Comment by ignaciosantise** [comment]
Cool @idlatest! thanks for the feedback. Closing the issue

Solution here https://github.com/WalletConnect/react-native-examples/issues/26#issuecomment-1513171009
