### ISSUE TITLE
TypeError: Cannot read property 'getItem' of undefined on tokenContraact.approve

### ISSUE THREAD

**Issue by BejoJeffrin23** [WalletConnect/react-native-examples#32]
Hi , iam trying to make a swap function in trust wallet using wallet connect V2 . I check the approved token amount and if there is no sufficient approval amount , i call the approve function of the contract . 

 await tokenContract.allowance(  account,routerAddress) is working fine 
 
 but await tokenContract.approve(routerAddress,  ethers.utils.parseUnits('1', 6),{gasLimit: '100000'})  
 
 is throwing error saying TypeError: Cannot read property 'getItem' of undefined

**Comment by ignaciosantise** [comment]
Hey @BejoJeffrin23, this issue is related with https://github.com/WalletConnect/react-native-examples/issues/26
