### ISSUE TITLE
Can't connect with walletconnect to create session

### ISSUE THREAD

**Issue by benduongquangmobile** [WalletConnect/react-native-examples#34]
I try to build and create connect, 3 days ago I still can create the connect but today, it's showing this. Please help.

![341207995_259466353148218_6526793067450878564_n](https://user-images.githubusercontent.com/92382730/233014406-d0371267-7663-4db2-8d17-8eb7e9b999be.jpg)
![Screenshot 2023-04-19 at 14 23 10](https://user-images.githubusercontent.com/92382730/233014494-a642aac0-86c2-4114-9dc3-f047c6afed08.png)

**Comment by KayCm** [comment]
delete rpcMap.

like this:

rpcMap:{}

https://github.com/WalletConnect/react-native-examples/issues/14

**Comment by benduongquangmobile** [comment]
still error
<img width="1077" alt="Screenshot 2023-04-20 at 18 44 18" src="https://user-images.githubusercontent.com/92382730/233356240-cef8c421-5d98-41b4-b54b-097ee50da7d6.png">

**Comment by ignaciosantise** [comment]
hey @benduongquangmobile, check this comment https://github.com/WalletConnect/react-native-examples/issues/26#issuecomment-1513171009
