### ISSUE TITLE
can't connect with metamask

### ISSUE THREAD

**Issue by benduongquangmobile** [WalletConnect/react-native-examples#37]
https://user-images.githubusercontent.com/92382730/233547586-68c084a8-89b4-4cd6-bbff-d8466bb4f244.mp4

**Comment by ignaciosantise** [comment]
@benduongquangmobile MetaMask is still using WalletConnect v1.0, and the dapp example only supports v2.

**Comment by ignaciosantise** [comment]
Im closing this issue, as it's not related with the SDK but with MetaMask.
