### ISSUE TITLE
Readme link to react native guide is broken

### ISSUE THREAD

**Issue by bogdan-marian** [WalletConnect/react-native-examples#40]
We have this in readme of this project

Read through our [JS-React Native guide](https://docs.walletconnect.com/2.0/javascript/guides/react-native)

If you novigate there you get `Page Not Found`

Also you have to understand that for the most part developers would most likely want to write web3 apps sot they are not interested to develop an wallet but to connect to 1. This is not reflected in the way intro and documentation is structured. It is very confusing and I actualy tok me cupple of hours to understand that you have no client example on how to connect to a wallet. from a daap react native app that neds to use walletconnect.

**Comment by ignaciosantise** [comment]
hey @bogdan-marian, i opened a PR to fix the link to our guides. Thanks for the feedback.

About the examples, check our [guides](https://docs.walletconnect.com/2.0/reactnative/overview) and you'll see documentation and examples for:
* Web3Modal -> use it to connect your dapp to wallets
* Web3Wallet -> use it to connect your wallet to dapps

In your case, you should check the Web3Modal docs and examples. Our SDK is currently in alpha version, but you can try it
