### ISSUE TITLE
Multichain

### ISSUE THREAD

**Issue by MuhammadZubair210** [WalletConnect/react-native-examples#44]
Hello, Can you let me know about sending polygon or solana tokens with react native. Is it supported in this sdk right now.

Thank you.

**Comment by ignaciosantise** [comment]
Hey @MuhammadZubair210 👋 You can connect to polygon chain with no issues. You can try changing the chain to `eip155:137` here: https://github.com/WalletConnect/react-native-examples/blob/5b61aa5f87a274129fc3b1ff7e34a085205facc9/dapps/ModalUProvider/src/utils/ConfigUtils.ts#L18

Regarding Solana support, this package uses the universal-provider, which supports solana. But we didn't test it yet, but you can give it a try.
