### ISSUE TITLE
 Error for initializing [TypeError: Cannot read property 'Core' of undefined]

### ISSUE THREAD

**Issue by edenmeshulam** [WalletConnect/react-native-examples#45]
Try to use wallet conenct **v2 latest** versions but get this error in initialized 
 Error for initializing [TypeError: Cannot read property 'Core' of undefined]
`
   core = new Core({
        projectId: 'MY_PROJECT_ID',
        relayUrl: 'wss://relay.walletconnect.com',
    });
`
Please HELP!

Using:
TrustWalletCore SDK latest
React native 0.66
IOS + Xcode Latest

**Comment by edenmeshulam** [comment]
Change @fase-text-encoding to @text-encoding fixed the problem

**Comment by ric344** [comment]
how you have debug this error? facing the same

**Comment by edenmeshulam** [comment]
> how you have debug this error? facing the same

Change @fase-text-encoding to @text-encoding fixed the problem

**Comment by ric344** [comment]
there is no package named @text-encoding ?

**Comment by edenmeshulam** [comment]
> 

Sorry, meant to this pack:   **"text-encoding": "^0.7.0"**

**Comment by ric344** [comment]
getting this error: Unable to resolve "@text-encoding" from "src/screens/App.tsx"

**Comment by ric344** [comment]
still getting this error: {"context": "core"} {"context": "core/relayer"} [TypeError: undefined is not a function]

**Comment by edenmeshulam** [comment]
Which version of react native you are using?

**Comment by ric344** [comment]
"react-native": "0.71.8"

**Comment by edenmeshulam** [comment]
You need to imported that 
import 'text-encoding';
in the main index file

**Comment by ric344** [comment]
already in that.
are you able to test this example on your local?

**Comment by edenmeshulam** [comment]
Yes 👍🏻
