### ISSUE TITLE
Screens[viewstack]......... undefined is not a function

### ISSUE THREAD

**Issue by abhayn360** [WalletConnect/react-native-examples#46]
sometimes the app shows an error undefined is not a function in explorermodal.tsx

` {SCREENS[viewStack?.at(-1) ?? INITIAL_ROUTE]}`

**Comment by ignaciosantise** [comment]
hey @abhayn360 👋  thanks for reaching out! 

Please check the latest updates of the dapp example, `ExplorerModal.tsx` has been [removed](https://github.com/WalletConnect/react-native-examples/pull/36) and now the example uses https://github.com/WalletConnect/web3modal-react-native. 

The package is still in alpha, but you will have a better experience. Closing the issue as it's related with deprecated code.
