### ISSUE TITLE
[Question] auto navigation to wallet app on transaction submit

### ISSUE THREAD

**Issue by itsnyx** [WalletConnect/react-native-examples#47]
Hello, thanks for this awesome example,
i have question on submitting transaction.

i have this method of sending transaction:
first i define tx object :

```
  const tx = await formatTestTransaction(
      'eip155:' +
        chainId +
        ':' +
        address +
        ':' +
        destination +
        ':' +
        Web3.utils.numberToHex(Web3.utils.toWei(amount, 'ether')),
    );

```

then i initiate transaction with : 
`    const txHash = await web3Provider.send('eth_sendTransaction', [tx]);
`
when i connect my wallet with qr code and its in another mobile phone i can see and confirm or reject the transaction but when its connected to a wallet app on the same phone it dosent auto navigate to the connected wallet and i have to switch to the wallet app manually and when i do this i dont see the transaction popup on the wallet app!

what is the correct way to achieve this ?

**Comment by itsnyx** [comment]
i also tried this method : 
https://github.com/WalletConnect/react-native-examples/issues/13#issue-1591601060

this one was better but still didn’t auto navigate to the wallet app

**Comment by ignaciosantise** [comment]
hey @itsnyx 👋  Thanks for reaching!

Are you using the latest example of the dapp? If so, which wallet are you using? Did you try with other wallets?

To navigate, we use wallet's universal link, but it could fail if they uploaded the wrong data to our [Explorer](https://walletconnect.com/explorer) API

**Comment by itsnyx** [comment]
@ignaciosantise  Im testing with v2 wallets like trust

can you please add example of sending transaction in the example or you can also reply here ?

**Comment by ignaciosantise** [comment]
@itsnyx the latest version of the [dapp](https://github.com/WalletConnect/react-native-examples/tree/main/dapps/v2Explorer) has a few eth methods to test

**Comment by itsnyx** [comment]
@ignaciosantise i managed to get it working with the latest version thanks
