### ISSUE TITLE
[Question] sending tokens under ethereum network

### ISSUE THREAD

**Issue by itsnyx** [WalletConnect/react-native-examples#52]
Hello, 
is it possible to send a token to another address instead of ethereum (or smart chain) it self ?

is this possible with wallet connect? 
if it is can someone give a code example ?
 
thanks

**Comment by ignaciosantise** [comment]
hey @itsnyx 👋  yes, you can change the address to the one you want. In our dapp example, you can modify [this](https://github.com/WalletConnect/react-native-examples/blob/30754b072c6465d06edc1bd3bcdc009493ffc51a/dapps/v2Explorer/src/utils/MethodUtil.ts#L148C9-L148C9) to a new address
