### ISSUE TITLE
Issues trying to run the example

### ISSUE THREAD

**Issue by DavidsDvm** [WalletConnect/react-native-examples#6]
Hi there, I am currently working on a project that is trying to use walletconnect v2 using react native, I just read the docs, but I still having the same issue, so I come here to check the examples and when I try to run this project I got the same issue again (I don't know if is a problem with my config or if it is something related to walletconnect)

Here is the image of the actual error (PD: I know that there is the ENV_PROJECT_ID visible but I currently using it for testing purposes so there is not problem if you can see it, there you can see too that the logger is printing undefined but on the route it is using the variables correctly IDK why):

![image](https://user-images.githubusercontent.com/33884578/212185332-5824ff6e-2e84-4cb3-ad7e-1458f1e8c2b9.png)

The error is being given when I try to run both types of wallets (rn_cli_wallet & rn_expo_wallet)

If it help you to identify the problem I am using the next device to test: (Installing APK 'app-debug.apk' on 'Pixel_3a_API_33_x86_64(AVD) - 13' for :app:debug)

Thanks in advance for your help and support if you need more information about the problem I will be open to share it with you.

**Comment by 0xgareth** [comment]
@DavidsDvm per readme you can fix this by running `cp .env.example .env` and replacing ENV_PROJECT_ID with your own ProjectId from https://cloud.walletconnect.com/

**Comment by crypblizz8** [comment]
Thanks @DavidsDvm and @0xgareth, did copying the `.env `config help resolve the situation?

**Comment by DavidsDvm** [comment]
The `.env` was already set when I create the issue, my actual `.env` config is the following:

```
ENV_PROJECT_ID=2860a12939ec6964408f63eee5e02baa
ENV_RELAY_URL=wss://relay.walletconnect.com
```

If you check the screenshot that I attached before, on the URL could be seen the ID and I was used correctly. Check the following image (is the same as the above) where I put a red line on the URL, to show you that the ID is being used correctly:

![image](https://user-images.githubusercontent.com/33884578/212713505-b8fd1125-44f2-4718-b491-b5623c95de93.png)

like I said before: I know that there is the ENV_PROJECT_ID visible but I currently using it for testing purposes so there is not problem if you can see it

**Comment by crypblizz8** [comment]
Thanks @DavidsDvm, I tried the `ProjectID` since it is also for testing purposes. I reproduced the same error as well. I used a fresh ProjectID and it seemed to resolve the issue.

Have you potentially added any domains to the `AllowList` in our Cloud App? Perhaps resetting that one / making a new project might help with this?

**Comment by DavidsDvm** [comment]
Thanks @crypblizz8, this solved the problem
