### ISSUE TITLE
Cannot read property "seed" of null

### ISSUE THREAD

**Issue by mendsalbert** [WalletConnect/react-native-examples#61]
<img width="324" alt="Screenshot 2023-05-24 at 6 58 05 AM" src="https://github.com/WalletConnect/react-native-examples/assets/40429398/9db7e74f-0857-4ae5-9b06-c5e56c0391c0">

**Comment by ignaciosantise** [comment]
@mendsalbert can you give some context of the error? Which example are you using? Can you also write the steps to reproduce the error?

**Comment by ignaciosantise** [comment]
Closing as i cannot reproduce it. I'll reopen if more info is provided.
