### ISSUE TITLE
can't find variable: BigInt

### ISSUE THREAD

**Issue by therealharpaljadeja** [WalletConnect/react-native-examples#64]
I am trying to upgrade from WalletConnect v1 to v2 in react native, I am using `@walletconnect/react-native-dapp`

I get the following error the moment the `Web3Button` comes into view

![image](https://github.com/WalletConnect/react-native-examples/assets/38040789/8450bc34-a2bd-491a-9aa3-0f79b161d6ab)

**Comment by ignaciosantise** [comment]
hey @therealharpaljadeja 👋 Thanks for reaching out!

A couple of questions:
* Which version of `react-native` are you using? 
* Are you following the [docs](https://docs.walletconnect.com/2.0/reactnative/web3modal/Installation)?
* Does the error appear on iOS too?

**Comment by therealharpaljadeja** [comment]
- I am using `react-native` version `0.70.8`
- Yes, I am following docs I couldn't run the npx pod-install command though
- No error in iOS

**Comment by therealharpaljadeja** [comment]
I am migrating this [project](https://github.com/celo-org/celo-composer/tree/main/packages/react-native-app) to WalletConnect v2

**Comment by therealharpaljadeja** [comment]
Life saver, polyfill worked!

**Comment by ignaciosantise** [comment]
That's great @therealharpaljadeja 🎉 Did you have any other issue while migrating? Any feedback?

**Comment by therealharpaljadeja** [comment]
No @ignaciosantise, thanks for your help! 

The `react-native-examples` repo is good enough to get started!
