### ISSUE TITLE
docs: Best way to resume/restore a WC session? 

### ISSUE THREAD

**Issue by 1a35e1** [WalletConnect/react-native-examples#65]
Thanks for getting the alpha of the sign client out. It's helped us remove a lot of boilerplate.

In the repo once we have successfully connected a wallet we store the `clientId`.

It would be useful to understand which way you guys are leaning in regards to session management. 

Specifically resuming a previously WalletConnect session.

**Comment by ignaciosantise** [comment]
hi @1a35e1 👋  can you give some more context? Is it related to Web3Modal (dapp side) or Web3Wallet (wallet side)?

**Comment by 1a35e1** [comment]
It's related to the dapp side from this example.

https://github.com/WalletConnect/react-native-examples/blob/c5bed5c19bdf1e1b34de9a3ad731364bf433f592/dapps/v2Explorer/src/screens/App.tsx#L39 

Once we get the `clientId` what is the best way to programmatically restore the session?

**Comment by 1a35e1** [comment]
Update:

So as a workaround I've got it working by rending the `<Web3Modal />` in my of my child components.

I can see there is some session management logic within the <Web3Modal />, looking at the `onConnect` function, which I believe was the missing link. Will there be a way to have this logic execute without rendering the modal component in my nested React components?

**Comment by ignaciosantise** [comment]
@1a35e1 as you said, the session is recovered when `Web3Modal` is rendered. The initialization logic is inside that component, but i'll think a way of extracting it elsewhere

**Comment by ignaciosantise** [comment]
For now, the only way to restore the session is by using `Web3Modal` component.
