### ISSUE TITLE
Metamask Is Not Present in Wallet list how can we connect metamask 

### ISSUE THREAD

**Issue by pavandugariya** [WalletConnect/react-native-examples#66]
Metamask Is Not Present in Wallet list how can we connect metamask

**Comment by pavandugariya** [comment]
@ignaciosantise  thank very much for the responding 

but when i use v2 its not connected with meta mask it only redirect not showing connect popup

**Comment by ignaciosantise** [comment]
@pavandugariya you're welcome!

v2 wont work with metamask because they have to update their app. That's why the popup doesn't show.
