### ISSUE TITLE
[bug]: Expo Replicated {"context": "client"} undefined is not a function when build the app in Android

### ISSUE THREAD

**Issue by bdtren** [WalletConnect/react-native-examples#79]
### Description

Hi everyone,

I replicated this issue when try to connect a dApp with Wallet App which is writing using expo. And the issue is only replicated in Android device.

issue detail:
```
 ERROR  {"context": "core"} undefined is not a function
 ERROR  {"context": "client"} undefined is not a function
 ERROR  {"context": "core"} undefined is not a function
```

Here is the version of dependencies I used:
```
"@walletconnect/react-native-compat": "^2.8.6",
"@walletconnect/utils": "^2.8.6",
"@walletconnect/web3wallet": "^1.8.5",
...
"expo": "~48.0.18",
"react-native": "0.71.8",
```
I also able to replicated that issue in the example App [web3wallet_tutorial](https://github.com/WalletConnect/react-native-examples/tree/main/wallets/web3wallet_tutorial)

<img alt="web3wallet_tutorial-connect_error" src="https://github-production-user-asset-6210df.s3.amazonaws.com/29066552/250474293-29ead4cc-007d-4d8f-bdd1-3558efaad113.jpg" width="400"/>

I checked though the library code, and think the issue is from [x25519.generateKeyPair()](https://github.com/WalletConnect/walletconnect-monorepo/blob/c20eb6282d3da059be0ca3103d67ba188a3d4e79/packages/utils/src/crypto.ts#L23) as it can only be called succeed max 2 times in expo.

### Issue Environment

- [ ] dapps/v2Explorer
- [ ] wallets/rn_cli_wallet
- [ ] wallets/rn_cli_wallet_068_5
- [ ] wallets/expo_wallet
- [X] wallets/web3wallet_tutorial
- [X] In my own code

### Output of `npx react-native info`

System:
    OS: macOS 12.6.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 2.04 GB / 32.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
    Yarn: 1.22.18 - ~/.yarn/bin/yarn
    npm: 8.1.0 - ~/.nvm/versions/node/v16.13.0/bin/npm
    Watchman: 2022.06.06.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.3 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK:
      API Levels: 28, 29, 30, 31, 32, 33, 34
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.2, 30.0.3, 31.0.0, 33.0.0
      System Images: android-23 | Google APIs Intel x86 Atom_64, android-29 | Google Play Intel x86 Atom, android-30 | Google APIs ARM 64 v8a, android-30 | Google APIs Intel x86 Atom, android-30 | Google APIs Intel x86 Atom_64
      Android NDK: Not Found
  IDEs:
    Android Studio: 2021.3 AI-213.7172.25.2113.9123335
    Xcode: 14.1/14B47b - /usr/bin/xcodebuild
  Languages:
    Java: 11.0.12 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.2.0 => 18.2.0 
    react-native: 0.71.4 => 0.71.4 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

- Do `yarn install`
- Do `npx expo start --clear`
- Connect to Android device(tested Android 9, 12 and 13) open App using `Expo Go`
- Enter Wallet connect url
- Press "Pair Session" (sometime issue appear in this step)
- Popup show, press "Accept"
- Replicated error `{"context": "client"} undefined is not a function`

### Snack, code example, screenshot, or link to a repository

I tried that function in both `rn_cli_wallet` and `rn_expo_wallet` by adding `@stablelib/x25519`, `uint8arrays`and wrote this code:
```
// import {
//   deriveSymKey,
//   generateKeyPair,
// } from "@walletconnect/utils";
import * as x25519 from "@stablelib/x25519";
import {toString} from "uint8arrays";
const BASE16 = 'base16';

const generateKeyPair = () => {
  try {
    const keyPair = x25519.generateKeyPair();
    const kp = {
      privateKey: toString(keyPair.secretKey, BASE16),
      publicKey: toString(keyPair.publicKey, BASE16),
    };
    console.log('generateKeyPair', kp);
    return kp;
  } catch (e) {
    console.log('generateKeyPair.error', e);
  }
  return {
    privateKey: '',
    publicKey: '',
  };
};

const selfKeyPair = generateKeyPair();
const selfKeyPair1 = generateKeyPair();
const selfKeyPair2 = generateKeyPair();
const selfKeyPair3 = generateKeyPair();
const selfKeyPair4 = generateKeyPair();
const selfKeyPair5 = generateKeyPair();
```
The result is like this:
![web3_wallet_test](https://github.com/WalletConnect/react-native-examples/assets/29066552/f7fa9293-014a-484c-b0a8-15f5bf0c692a)

issue also replicated when using `generateKeyPair()` of `@walletconnect/utils`

**Comment by Mostafatalaat770** [comment]
I can confirm it happens on Andriod

**Comment by Mostafatalaat770** [comment]
@ignaciosantise maybe you can help 😃

**Comment by bdtren** [comment]
Ah, I found the root cause of it, the issue is from `react-native-get-random-values` that somehow `global.expo.modules.ExpoCrypto.getRandomValues` is undefined.

My temp solution is take the `insecureRandomValues()` out and use it directly.

**Comment by Mostafatalaat770** [comment]
@bdtren you can test using this shim https://github.com/WalletConnect/modal-react-native/blob/main/example/expo-crypto-shim.js, it fixes the `getRandomValues` problem. I guess it should be fixed by Expo 49.

**Comment by ignaciosantise** [comment]
@bdtren as @Mostafatalaat770 said, there's an issue with Expo 48 and `react-native-get-random-values`. Importing that custom shim should solve the problem

Related docs: https://docs.walletconnect.com/2.0/reactnative/walletconnectmodal/installation#additional-setup-for-expo-sdk-48

`react-native-get-random-values 1.9.0` solves the issue, but it's not available for expo 48. I didn't checked expo 49 yet

**Comment by ignaciosantise** [comment]
@bdtren did you solve the issue?

**Comment by bdtren** [comment]
@ignaciosantise Yes. 
Shim not working from my side by the way, even when I put it to the top of the file, before import `@walletconnect/react-native-compat`. So my only solution is edit `react-native-get-random-values` and patch-package it.
