### ISSUE TITLE
[enhancement]: Ensure Expo all works for Web

### ISSUE THREAD

**Issue by crypblizz8** [WalletConnect/react-native-examples#87]
### Description

Some developers may want to use Web.

Low Priority: P3

### Issue Environment

- [X] dapps/v2Explorer
- [X] wallets/rn_cli_wallet
- [X] wallets/rn_cli_wallet_068_5
- [X] wallets/expo_wallet
- [X] wallets/web3wallet_tutorial
- [X] In my own code

### Output of `npx react-native info`

N/A

### Steps to reproduce

N/A

### Snack, code example, screenshot, or link to a repository

N/A

**Comment by krasiva711** [comment]
[enhancement]: Ensure Expo all works for Web[github]()
