### ISSUE TITLE
[bug]:   {"context": "core"} {"context": "core/relayer"} [Error: WebSocket connection closed abnormally with code: 3000 (Authorization error: JWT validation error: JWT Token is expired: Some(1691558934))]

### ISSUE THREAD

**Issue by vishalpql** [WalletConnect/react-native-examples#92]
### Description

{"context": "core"} {"context": "core/relayer"} [Error: WebSocket connection closed abnormally with code: 3000 (Authorization error: JWT validation error: JWT Token is expired: Some(1691558934))]

Getting this error when app initialise first time
and error produced multiple time, not able to connect with dApp

used **rn_cli_wallet_068_5** _react native project_

### Issue Environment

- [ ] dapps/v2Explorer
- [ ] wallets/rn_cli_wallet
- [X] wallets/rn_cli_wallet_068_5
- [ ] wallets/expo_wallet
- [ ] wallets/web3wallet_tutorial
- [X] In my own code

### Output of `npx react-native info`

System:
    OS: macOS 13.4
    CPU: (8) arm64 Apple M1
    Memory: 99.02 MB / 8.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 20.3.0 - /opt/homebrew/bin/node
    Yarn: 1.22.18 - /opt/homebrew/bin/yarn
    npm: 9.6.7 - /opt/homebrew/bin/npm
    Watchman: 2023.06.12.00 - /opt/homebrew/bin/watchman
  Managers:
    CocoaPods: 1.12.1 - /opt/homebrew/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 22.1, iOS 16.1, macOS 13.0, tvOS 16.1, watchOS 9.1
    Android SDK: Not Found
  IDEs:
    Android Studio: 2022.1 AI-221.6008.13.2211.9514443
    Xcode: 14.1/14B47b - /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild
  Languages:
    Java: 11.0.18 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2 
    react-native: 0.68.5 => 0.68.5 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found

### Steps to reproduce

run: yarn install
update ProjectID
start bundler server **yarn start**
install the app in android emulator
when app starts first time get this error multiple time

### Snack, code example, screenshot, or link to a repository

import {Core} from '@walletconnect/core';
import {ICore} from '@walletconnect/types';
import {Web3Wallet, IWeb3Wallet} from '@walletconnect/web3wallet';
export let web3wallet: IWeb3Wallet;
export let core: ICore;
export let currentETHAddress: string;

// @ts-expect-error - env is a virtualised module via Babel config.
import {ENV_PROJECT_ID, ENV_RELAY_URL} from '@env';
import {createOrRestoreEIP155Wallet} from './EIP155Wallet';

export async function createWeb3Wallet() {

  core = new Core({
    projectId: '4cc681786f4eda7694e95207c98720d3',
    relayUrl: 'wss://relay.walletconnect.com',
  });

  const {eip155Addresses} = await createOrRestoreEIP155Wallet();
  currentETHAddress = eip155Addresses[0];

  web3wallet = await Web3Wallet.init({
    core,
    metadata: {
      name: 'React Native Web3Wallet',
      description: 'ReactNative Web3Wallet',
      url: 'https://walletconnect.com/',
      icons: ['https://avatars.githubusercontent.com/u/37784886'],
    },
  });
}

export async function _pair(params: {uri: string}) {
  return await core.pairing.pair({uri: params.uri});
}

<img width="810" alt="Screenshot 2023-08-09 at 3 20 36 PM" src="https://github.com/WalletConnect/react-native-examples/assets/103259178/e2a600b1-7852-450e-96a4-56ba3b181eff">

**Comment by ignaciosantise** [comment]
hey @vishalpql this issue happens when you have the datetime settings of your emulator bad configured, resulting in the JWT expiring. Can you check your datetime settings and ensure its ok?

**Comment by arun1940** [comment]
How can I resolve my configuration issue? My date and time settings seem to be correct.

**Comment by ignaciosantise** [comment]
This issue happens if the device/emulator has wrong date/time config
